version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
  ApplicationStart:
    - location: applicationStart.sh
      timeout: 300
