parameters:
- name: myVariable
  type: string
  default: ''
# trigger:
# - none
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: 'Develop'
  displayName: 'Develop'
  jobs:
  - job: 'Develop_Build'
    displayName: 'Build job'
  
    steps:
    - bash: |
        # echo "My variable value is: ${{ parameters.myVariable }}"
        # git clone --single-branch --branch ${{ parameters.myVariable }} https://github.com/mangeshnag9651/blue-green.git
        # cd blue-green
        # cat abc.yml
        ls
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Build React Application'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/build'
        ArtifactName: 'react-app'
      displayName: 'Publish Artifact'


- stage: 'Stage'
  jobs: 
  - deployment: 'DeployToStage'
    environment: 'Build-Stage-Branch-Promote'
    strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            # - bash: |
            #         echo "My variable value is: ${{ parameters.myVariable }}"
            #         git clone --single-branch --branch ${{ parameters.myVariable }} https://github.com/mangeshnag9651/react3124.git
            #         cd react3124
            #         cat abc.yml
            #         ls
            #         pwd
            - task: NodeTool@0
              inputs:
                versionSpec: '14.x'
              displayName: 'Install Node.js'
              
            - bash: |
                    echo "My variable value is: ${{ parameters.myVariable }}"
                    git clone --single-branch --branch ${{ parameters.myVariable }} https://github.com/mangeshnag9651/react3124.git
                    cd react3124
                    cat abc.yml
                    ls
                    pwd

            - script: |
                cd react3124
                npm install
                npm run build
              displayName: 'Build React Application'

            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.SourcesDirectory)/react3124/build'
                ArtifactName: 'react-app-stage'
                publishLocation: 'Container'
              displayName: 'Publish Artifact'