# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - none

parameters:
- name: myVariable
  type: string
  default: 'blue'
  values:
    - blue
    - green

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build React Application'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/build'
      ArtifactName: 'react-app'
    displayName: 'Publish Artifact'

  # - bash: |
  #         ls
  #         pwd
  #         cd $(Build.SourcesDirectory)/build
  #         cp /home/vsts/work/1/s/appspec.yml .
  #         cp -r /home/vsts/work/1/s/before_install.sh .
  #         cp -r /home/vsts/work/1/s/applicationStart.sh .
  #         cp -r /home/vsts/work/1/s/install.sh .
  #         ls
  #         zip -r react-build.zip *
  #         pwd
  #         ls 
  #   displayName: 'Archive build'

  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws-s3-connection'
      regionName: 'ap-south-1'
      bucketName: 'deployment3434'
      sourceFolder: '$(Build.SourcesDirectory)/build'
      globExpressions: '**'
      createBucket: true
  
  - task: SystemsManagerRunCommand@1
    inputs:
      awsCredentials: 'aws-s3-connection'
      regionName: 'ap-south-1'
      documentName: 'AWS-RunShellScript'
      documentParameters: '{"commands":["aws s3 cp s3://deployment3434 /var/www/html --recursive"],"workingDirectory":[""],"executionTimeout":["3600"]}'
      instanceSelector: 'fromBuildVariable'
      instanceBuildVariable: 'parameters.myVariable'

  # - task: CodeDeployDeployApplication@1
  #   inputs:
  #     awsCredentials: 'aws-S3-Connection'
  #     regionName: 'ap-south-1'
  #     applicationName: 'Blue-Green'
  #     deploymentGroupName: 'Blue-Green'
  #     deploymentRevisionSource: 's3'
  #     bucketName: 'deployment3434'
  #     bundleKey: 'react-build.zip'