parameters:
- name: myVariable
  type: string
  default: ''
 
trigger:
- none
 
jobs:
- job: Build
  displayName: 'Build job'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # - bash: |
  #     echo "My variable value is: ${{ parameters.myVariable }}"
  #     git clone --single-branch --branch ${{ parameters.myVariable }} https://github.com/mangeshnag9651/blue-green.git
  #     cd blue-green
  #     cat abc.yml
  #     ls
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build React Application'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/build'
      ArtifactName: 'react-app'
    displayName: 'Publish Artifact'


